[tool.poetry]
name = "fastapi-load-test"
version = "0.1.0"
description = ""
authors = ["Jingwei Kang"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.112.1"}
aiohttp = "^3.10.5"
requests = "^2.32.3"
