{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_requests_total,app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_requests_total{app_name=\"$app_name\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_duration_seconds_sum{app_name=\"$app_name\"} / fastapi_requests_duration_seconds_count{app_name=\"$app_name\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_exceptions_total{app_name=\"$app_name\"}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (fastapi_responses_total{app_name=\"$app_name\", status_code=~\"2.*\", path!=\"/metrics\"}) / sum by(path) (fastapi_responses_total{app_name=\"$app_name\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (fastapi_responses_total{app_name=\"$app_name\", status_code=~\"5.*\", path!=\"/metrics\"}) / sum by(path) (fastapi_responses_total{app_name=\"$app_name\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(path, le) (rate(fastapi_requests_duration_seconds_milliseconds_bucket{app_name=\"$app_name\", path!=\"/metrics\"}[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "fastapi_requests_in_progress{app_name=\"$app_name\", path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fastapi_requests_total{app_name=\"$app_name\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Sync Request Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(path, le) (rate(fastapi_requests_duration_seconds_milliseconds_bucket{app_name=\"$app_name\", path=\"/sync-delay/{delay_ms}\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Async Request Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum by(path, le) (rate(fastapi_requests_duration_seconds_milliseconds_bucket{app_name=\"$app_name\", path=\"/async-delay/{delay_ms}\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "filters": [
      { "id": "32512b3c", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$app_name" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}